services:
    napas_extra_form.form.type.us_states:
        class: Napas\FormExtraBundle\Form\UsStatesType
        tags:
            - { name: form.type, alias: us_states }

    napas_extra_form.twig.states_extension:
        class: Napas\FormExtraBundle\Twig\StatesExtension
        tags:
            - { name: twig.extension }
